default: &default
  adapter: postgresql
  encoding: unicode
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>
  username: <%= ENV.fetch("POSTGRES_USER")     { "postgres" }  %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>
  host:     <%= ENV.fetch("POSTGRES_HOST")     { "localhost" } %>
  port:     <%= ENV.fetch("POSTGRES_PORT")     { 6000 } %>

development:
  <<: *default
  database: remember_car_development

test:
  <<: *default
  database: remember_car_test

production:
  adapter: postgresql
  encoding: unicode
  database: remember_car_production
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>
  url: <%= ENV["DATABASE_CONNECTION_POOL_URL"] || ENV["DATABASE_URL"] %>
